### ISSUE TITLE
No sensor in HA 2025.8

### ISSUE THREAD

**Issue by XandroTs** [wilds/hass-atonstorage#50]
After updating Home Assistant to 2025.8 all sensors disappeared, only binary sensors remained

Registratore: homeassistant.components.sensor
Fonte: helpers/entity_platform.py:451
Integrazione: Sensore (documentazione, problemi)
Prima occorrenza: 07:54:22 (1 occorrenza)
Ultimo accesso: 07:54:22

Error while setting up atonstorage platform for sensor: IntegrationSensor.__init__() missing 1 required positional argument: 'hass'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.13/site-packages/homeassistant/helpers/entity_platform.py", line 451, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/home/homeassistant/.homeassistant/custom_components/atonstorage/sensor.py", line 394, in async_setup_entry
    entities = _create_entities(hass, entry)
  File "/home/homeassistant/.homeassistant/custom_components/atonstorage/sensor.py", line 420, in _create_entities
    AtonStorageIntegrationSensor(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        integration_method="left",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        username=username,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/homeassistant/.homeassistant/custom_components/atonstorage/sensor.py", line 533, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        integration_method=integration_method,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        max_sub_interval=None,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: IntegrationSensor.__init__() missing 1 required positional argument: 'hass'

**Comment by Majikmonke** [comment]
I have the same issues, entities went from 43 down to 11following HA update

**Comment by FrancescoFdd5** [comment]
See #51

**Comment by Dev-Fabry** [comment]
Same for me, after update I have this error:

REST result could not be parsed as JSON
Source: custom_components/atonstorage/controller.py:133

and about all entities now "not available"

Rollback to 2025.7.4 (with "core update --version 2025.7.4" using HA CLI) and now all working again

**Comment by wilds** [comment]
Merged #51
